-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 03:58:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema doantotnghiep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doantotnghiep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doantotnghiep` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `doantotnghiep` ;

-- -----------------------------------------------------
-- Table `doantotnghiep`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`nhanvien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenTaiKhoan` VARCHAR(100) NULL DEFAULT NULL,
  `matKhau` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `sdt` VARCHAR(15) NULL DEFAULT NULL,
  `diaChi` TEXT NULL DEFAULT NULL,
  `hoTen` VARCHAR(100) NULL DEFAULT NULL,
  `vaiTro` VARCHAR(50) NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `ngayCapNhat` DATETIME NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`baocaothongke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`baocaothongke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loai` VARCHAR(50) NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `thoiGianBatDau` DATETIME NULL DEFAULT NULL,
  `thoiGianKetThuc` DATETIME NULL DEFAULT NULL,
  `tongSoDonHang` INT NULL DEFAULT NULL,
  `soLuongSanPhamNhapRa` INT NULL DEFAULT NULL,
  `tongDoanhThu` DECIMAL(10,2) NULL DEFAULT NULL,
  `nhanvien_id` INT NOT NULL,
  PRIMARY KEY (`id`, `nhanvien_id`),
  INDEX `fk_baocaothongke_nhanvien_idx` (`nhanvien_id` ASC) VISIBLE,
  CONSTRAINT `fk_baocaothongke_nhanvien`
    FOREIGN KEY (`nhanvien_id`)
    REFERENCES `doantotnghiep`.`nhanvien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`chitietdonhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`chitietdonhang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soLuong` INT NULL DEFAULT NULL,
  `gia` DECIMAL(10,2) NULL DEFAULT NULL,
  `donhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donhang_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`danhgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`danhgia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soSao` INT NULL DEFAULT NULL,
  `noiDung` TEXT NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`khachhang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenTaiKhoan` VARCHAR(100) NULL DEFAULT NULL,
  `matKhau` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `sdt` VARCHAR(15) NULL DEFAULT NULL,
  `diaChi` TEXT NULL DEFAULT NULL,
  `hoTen` VARCHAR(100) NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `ngayCapNhat` DATETIME NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  `danhgia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `danhgia_id`),
  INDEX `fk_khachhang_danhgia1_idx` (`danhgia_id` ASC) VISIBLE,
  CONSTRAINT `fk_khachhang_danhgia1`
    FOREIGN KEY (`danhgia_id`)
    REFERENCES `doantotnghiep`.`danhgia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`giohang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`giohang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tongTien` DECIMAL(10,2) NULL DEFAULT NULL,
  `tongSoLuong` INT NULL,
  `khachhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `khachhang_id`),
  INDEX `fk_giohang_khachhang1_idx` (`khachhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_giohang_khachhang1`
    FOREIGN KEY (`khachhang_id`)
    REFERENCES `doantotnghiep`.`khachhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`chitietgiohang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`chitietgiohang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soLuong` INT NULL DEFAULT NULL,
  `gia` DECIMAL(10,2) NULL DEFAULT NULL,
  `giohang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `giohang_id`),
  INDEX `fk_chitietgiohang_giohang1_idx` (`giohang_id` ASC) VISIBLE,
  CONSTRAINT `fk_chitietgiohang_giohang1`
    FOREIGN KEY (`giohang_id`)
    REFERENCES `doantotnghiep`.`giohang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`donhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`donhang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngayDatHang` DATETIME NULL DEFAULT NULL,
  `tongTien` DECIMAL(10,2) NULL DEFAULT NULL,
  `trangThai` VARCHAR(50) NULL DEFAULT NULL,
  `diaChiGiaoHang` TEXT NULL DEFAULT NULL,
  `sdt` VARCHAR(15) NULL DEFAULT NULL,
  `nhanvien_id` INT NOT NULL,
  `khachhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `nhanvien_id`, `khachhang_id`),
  INDEX `fk_donhang_nhanvien1_idx` (`nhanvien_id` ASC) VISIBLE,
  INDEX `fk_donhang_khachhang1_idx` (`khachhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_donhang_nhanvien1`
    FOREIGN KEY (`nhanvien_id`)
    REFERENCES `doantotnghiep`.`nhanvien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donhang_khachhang1`
    FOREIGN KEY (`khachhang_id`)
    REFERENCES `doantotnghiep`.`khachhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`phieuxuathang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`phieuxuathang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngayXuat` DATETIME NULL DEFAULT NULL,
  `tongSoLuong` INT NULL DEFAULT NULL,
  `tongGiaTri` DECIMAL(10,2) NULL DEFAULT NULL,
  `trangThai` VARCHAR(50) NULL DEFAULT NULL,
  `donhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donhang_id`),
  INDEX `fk_phieuxuathang_donhang1_idx` (`donhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_phieuxuathang_donhang1`
    FOREIGN KEY (`donhang_id`)
    REFERENCES `doantotnghiep`.`donhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`yeucautrahang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`yeucautrahang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngayYeuCau` DATETIME NULL DEFAULT NULL,
  `lyDo` TEXT NULL DEFAULT NULL,
  `hinhAnh` TEXT NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  `soLuongTra` INT NULL DEFAULT NULL,
  `giaTriTra` DECIMAL(10,2) NULL DEFAULT NULL,
  `soTienHoanTra` DECIMAL(10,2) NULL DEFAULT NULL,
  `ngayHoanTien` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`yeucaudoihang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`yeucaudoihang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngayYeuCau` DATETIME NULL DEFAULT NULL,
  `hinhAnh` TEXT NULL DEFAULT NULL,
  `lyDo` TEXT NULL DEFAULT NULL,
  `phiDoiHang` DECIMAL(10,2) NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  `soLuong` INT NULL DEFAULT NULL,
  `giaTri` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`chitietphieuxuat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`chitietphieuxuat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soLuong` INT NULL DEFAULT NULL,
  `baoHanh` DATETIME NULL DEFAULT NULL,
  `ghiChu` TEXT NULL DEFAULT NULL,
  `chitietdonhang_id` INT NOT NULL,
  `phieuxuathang_id` INT NOT NULL,
  `yeucautrahang_id` INT NOT NULL,
  `yeucaudoihang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chitietdonhang_id`, `phieuxuathang_id`, `yeucautrahang_id`, `yeucaudoihang_id`),
  INDEX `fk_chitietphieuxuat_chitietdonhang1_idx` (`chitietdonhang_id` ASC) VISIBLE,
  INDEX `fk_chitietphieuxuat_phieuxuathang1_idx` (`phieuxuathang_id` ASC) VISIBLE,
  INDEX `fk_chitietphieuxuat_yeucautrahang1_idx` (`yeucautrahang_id` ASC) VISIBLE,
  INDEX `fk_chitietphieuxuat_yeucaudoihang1_idx` (`yeucaudoihang_id` ASC) VISIBLE,
  CONSTRAINT `fk_chitietphieuxuat_chitietdonhang1`
    FOREIGN KEY (`chitietdonhang_id`)
    REFERENCES `doantotnghiep`.`chitietdonhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitietphieuxuat_phieuxuathang1`
    FOREIGN KEY (`phieuxuathang_id`)
    REFERENCES `doantotnghiep`.`phieuxuathang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitietphieuxuat_yeucautrahang1`
    FOREIGN KEY (`yeucautrahang_id`)
    REFERENCES `doantotnghiep`.`yeucautrahang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitietphieuxuat_yeucaudoihang1`
    FOREIGN KEY (`yeucaudoihang_id`)
    REFERENCES `doantotnghiep`.`yeucaudoihang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`danhmuc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`danhmuc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenDanhMuc` VARCHAR(100) NULL DEFAULT NULL,
  `moTa` TEXT NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `ngayCapNhat` DATETIME NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  `danhmuc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `danhmuc_id`),
  INDEX `fk_danhmuc_danhmuc1_idx` (`danhmuc_id` ASC) VISIBLE,
  CONSTRAINT `fk_danhmuc_danhmuc1`
    FOREIGN KEY (`danhmuc_id`)
    REFERENCES `doantotnghiep`.`danhmuc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`magiamgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`magiamgia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `giaTri` FLOAT NULL DEFAULT NULL,
  `ngayBatDau` DATETIME NULL DEFAULT NULL,
  `ngayKetThuc` DATETIME NULL DEFAULT NULL,
  `trangThai` VARCHAR(50) NULL DEFAULT NULL,
  `ma` TEXT NOT NULL,
  `donhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donhang_id`),
  INDEX `fk_magiamgia_donhang1_idx` (`donhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_magiamgia_donhang1`
    FOREIGN KEY (`donhang_id`)
    REFERENCES `doantotnghiep`.`donhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sanpham` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenSanPham` VARCHAR(100) NULL DEFAULT NULL,
  `moTa` TEXT NULL DEFAULT NULL,
  `gia` DECIMAL(10,2) NULL DEFAULT NULL,
  `hinhAnh` VARCHAR(255) NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `ngayCapNhat` DATETIME NULL DEFAULT NULL,
  `soLuong` INT NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  `chitietgiohang_id` INT NOT NULL,
  `chitietdonhang_id` INT NOT NULL,
  `danhgia_id` INT NOT NULL,
  `danhmuc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chitietgiohang_id`, `chitietdonhang_id`, `danhgia_id`, `danhmuc_id`),
  INDEX `fk_sanpham_chitietgiohang1_idx` (`chitietgiohang_id` ASC) VISIBLE,
  INDEX `fk_sanpham_chitietdonhang1_idx` (`chitietdonhang_id` ASC) VISIBLE,
  INDEX `fk_sanpham_danhgia1_idx` (`danhgia_id` ASC) VISIBLE,
  INDEX `fk_sanpham_danhmuc1_idx` (`danhmuc_id` ASC) VISIBLE,
  CONSTRAINT `fk_sanpham_chitietgiohang1`
    FOREIGN KEY (`chitietgiohang_id`)
    REFERENCES `doantotnghiep`.`chitietgiohang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sanpham_chitietdonhang1`
    FOREIGN KEY (`chitietdonhang_id`)
    REFERENCES `doantotnghiep`.`chitietdonhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sanpham_danhgia1`
    FOREIGN KEY (`danhgia_id`)
    REFERENCES `doantotnghiep`.`danhgia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sanpham_danhmuc1`
    FOREIGN KEY (`danhmuc_id`)
    REFERENCES `doantotnghiep`.`danhmuc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`seri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`seri` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `maSeri` VARCHAR(100) NULL DEFAULT NULL,
  `chitietphieuxuat_id` INT NOT NULL,
  `yeucautrahang_id` INT NOT NULL,
  `yeucaudoihang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chitietphieuxuat_id`, `yeucautrahang_id`, `yeucaudoihang_id`),
  INDEX `fk_seri_chitietphieuxuat1_idx` (`chitietphieuxuat_id` ASC) VISIBLE,
  INDEX `fk_seri_yeucautrahang1_idx` (`yeucautrahang_id` ASC) VISIBLE,
  INDEX `fk_seri_yeucaudoihang1_idx` (`yeucaudoihang_id` ASC) VISIBLE,
  CONSTRAINT `fk_seri_chitietphieuxuat1`
    FOREIGN KEY (`chitietphieuxuat_id`)
    REFERENCES `doantotnghiep`.`chitietphieuxuat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seri_yeucautrahang1`
    FOREIGN KEY (`yeucautrahang_id`)
    REFERENCES `doantotnghiep`.`yeucautrahang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seri_yeucaudoihang1`
    FOREIGN KEY (`yeucaudoihang_id`)
    REFERENCES `doantotnghiep`.`yeucaudoihang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`suachuabaotri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`suachuabaotri` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngayNhan` DATETIME NULL DEFAULT NULL,
  `ngayDuKienHoanThanh` DATETIME NULL DEFAULT NULL,
  `ngayHoanThanh` DATETIME NULL DEFAULT NULL,
  `chiPhi` DECIMAL(10,2) NULL DEFAULT NULL,
  `moTaLoi` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `tinhTrangKhiNhanSanPham` VARCHAR(100) NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sukien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sukien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenSuKien` VARCHAR(100) NULL DEFAULT NULL,
  `moTaSuKien` TEXT NULL DEFAULT NULL,
  `thoiGianBatDau` DATETIME NULL DEFAULT NULL,
  `thoiGianKetThuc` DATETIME NULL DEFAULT NULL,
  `loaiSuKien` VARCHAR(50) NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`thanhtoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`thanhtoan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phuongThuc` VARCHAR(50) NULL DEFAULT NULL,
  `trangThaiGiaoDich` VARCHAR(50) NULL DEFAULT NULL,
  `soTien` DECIMAL(10,2) NULL DEFAULT NULL,
  `maGiaoDichNCC` VARCHAR(100) NULL DEFAULT NULL,
  `ngayGiaoDich` DATETIME NULL DEFAULT NULL,
  `donhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donhang_id`),
  INDEX `fk_thanhtoan_donhang1_idx` (`donhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_thanhtoan_donhang1`
    FOREIGN KEY (`donhang_id`)
    REFERENCES `doantotnghiep`.`donhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`thongbao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`thongbao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tieuDe` VARCHAR(255) NULL DEFAULT NULL,
  `noiDung` TEXT NULL DEFAULT NULL,
  `ngayTao` DATETIME NULL DEFAULT NULL,
  `trangThai` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`vanchuyen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`vanchuyen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trangThaiVanChuyen` VARCHAR(50) NULL DEFAULT NULL,
  `ngayGiaoDuKien` DATETIME NULL DEFAULT NULL,
  `ngayThucTe` DATETIME NULL DEFAULT NULL,
  `maVanChuyen` VARCHAR(100) NULL DEFAULT NULL,
  `donhang_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donhang_id`),
  INDEX `fk_vanchuyen_donhang1_idx` (`donhang_id` ASC) VISIBLE,
  CONSTRAINT `fk_vanchuyen_donhang1`
    FOREIGN KEY (`donhang_id`)
    REFERENCES `doantotnghiep`.`donhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`thongbao_has_nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`thongbao_has_nhanvien` (
  `thongbao_id` INT NOT NULL,
  `nhanvien_id` INT NOT NULL,
  PRIMARY KEY (`thongbao_id`, `nhanvien_id`),
  INDEX `fk_thongbao_has_nhanvien_nhanvien1_idx` (`nhanvien_id` ASC) VISIBLE,
  INDEX `fk_thongbao_has_nhanvien_thongbao1_idx` (`thongbao_id` ASC) VISIBLE,
  CONSTRAINT `fk_thongbao_has_nhanvien_thongbao1`
    FOREIGN KEY (`thongbao_id`)
    REFERENCES `doantotnghiep`.`thongbao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thongbao_has_nhanvien_nhanvien1`
    FOREIGN KEY (`nhanvien_id`)
    REFERENCES `doantotnghiep`.`nhanvien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`thongbao_has_khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`thongbao_has_khachhang` (
  `thongbao_id` INT NOT NULL,
  `khachhang_id` INT NOT NULL,
  PRIMARY KEY (`thongbao_id`, `khachhang_id`),
  INDEX `fk_thongbao_has_khachhang_khachhang1_idx` (`khachhang_id` ASC) VISIBLE,
  INDEX `fk_thongbao_has_khachhang_thongbao1_idx` (`thongbao_id` ASC) VISIBLE,
  CONSTRAINT `fk_thongbao_has_khachhang_thongbao1`
    FOREIGN KEY (`thongbao_id`)
    REFERENCES `doantotnghiep`.`thongbao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thongbao_has_khachhang_khachhang1`
    FOREIGN KEY (`khachhang_id`)
    REFERENCES `doantotnghiep`.`khachhang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`chitietphieuxuat_has_suachuabaotri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`chitietphieuxuat_has_suachuabaotri` (
  `chitietphieuxuat_id` INT NOT NULL,
  `suachuabaotri_id` INT NOT NULL,
  PRIMARY KEY (`chitietphieuxuat_id`, `suachuabaotri_id`),
  INDEX `fk_chitietphieuxuat_has_suachuabaotri_suachuabaotri1_idx` (`suachuabaotri_id` ASC) VISIBLE,
  INDEX `fk_chitietphieuxuat_has_suachuabaotri_chitietphieuxuat1_idx` (`chitietphieuxuat_id` ASC) VISIBLE,
  CONSTRAINT `fk_chitietphieuxuat_has_suachuabaotri_chitietphieuxuat1`
    FOREIGN KEY (`chitietphieuxuat_id`)
    REFERENCES `doantotnghiep`.`chitietphieuxuat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chitietphieuxuat_has_suachuabaotri_suachuabaotri1`
    FOREIGN KEY (`suachuabaotri_id`)
    REFERENCES `doantotnghiep`.`suachuabaotri` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`nhanvien_has_suachuabaotri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`nhanvien_has_suachuabaotri` (
  `nhanvien_id` INT NOT NULL,
  `suachuabaotri_id` INT NOT NULL,
  PRIMARY KEY (`nhanvien_id`, `suachuabaotri_id`),
  INDEX `fk_nhanvien_has_suachuabaotri_suachuabaotri1_idx` (`suachuabaotri_id` ASC) VISIBLE,
  INDEX `fk_nhanvien_has_suachuabaotri_nhanvien1_idx` (`nhanvien_id` ASC) VISIBLE,
  CONSTRAINT `fk_nhanvien_has_suachuabaotri_nhanvien1`
    FOREIGN KEY (`nhanvien_id`)
    REFERENCES `doantotnghiep`.`nhanvien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nhanvien_has_suachuabaotri_suachuabaotri1`
    FOREIGN KEY (`suachuabaotri_id`)
    REFERENCES `doantotnghiep`.`suachuabaotri` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`sanpham_has_sukien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`sanpham_has_sukien` (
  `sanpham_id` INT NOT NULL,
  `sukien_id` INT NOT NULL,
  PRIMARY KEY (`sanpham_id`, `sukien_id`),
  INDEX `fk_sanpham_has_sukien_sukien1_idx` (`sukien_id` ASC) VISIBLE,
  INDEX `fk_sanpham_has_sukien_sanpham1_idx` (`sanpham_id` ASC) VISIBLE,
  CONSTRAINT `fk_sanpham_has_sukien_sanpham1`
    FOREIGN KEY (`sanpham_id`)
    REFERENCES `doantotnghiep`.`sanpham` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sanpham_has_sukien_sukien1`
    FOREIGN KEY (`sukien_id`)
    REFERENCES `doantotnghiep`.`sukien` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `doantotnghiep`.`seri_has_suachuabaotri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doantotnghiep`.`seri_has_suachuabaotri` (
  `seri_id` INT NOT NULL,
  `suachuabaotri_id` INT NOT NULL,
  PRIMARY KEY (`seri_id`, `suachuabaotri_id`),
  INDEX `fk_seri_has_suachuabaotri_suachuabaotri1_idx` (`suachuabaotri_id` ASC) VISIBLE,
  INDEX `fk_seri_has_suachuabaotri_seri1_idx` (`seri_id` ASC) VISIBLE,
  CONSTRAINT `fk_seri_has_suachuabaotri_seri1`
    FOREIGN KEY (`seri_id`)
    REFERENCES `doantotnghiep`.`seri` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seri_has_suachuabaotri_suachuabaotri1`
    FOREIGN KEY (`suachuabaotri_id`)
    REFERENCES `doantotnghiep`.`suachuabaotri` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
